"""p0_tenant_user

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-03
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column("code", sa.String(length=64), nullable=False, comment="租户编码(业务自然键)"),
        sa.Column("name", sa.String(length=128), nullable=False, comment="租户名称"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="状态"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间(UTC, ORM flush 触发)",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column("username", sa.String(length=64), nullable=False, comment="用户名"),
        sa.Column("password_hash", sa.String(length=255), nullable=False, comment="密码哈希"),
        sa.Column("nickname", sa.String(length=64), nullable=False, comment="昵称"),
        sa.Column("status", sa.String(length=16), nullable=False, comment="状态"),
        sa.Column("is_platform_admin", sa.Boolean(), nullable=False, comment="是否平台超管"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间(UTC, ORM flush 触发)",
        ),
        sa.Column("tenant_id", sa.BigInteger(), nullable=False, comment="所属租户 id"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], name="fk_users_tenant_id"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "username", name="uq_users_tenant_username"),
    )
    op.create_index(op.f("ix_users_tenant_id"), "users", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_tenant_id"), table_name="users")
    op.drop_table("users")
    op.drop_table("tenants")
    # ### end Alembic commands ###
