"""p2_audit_events —— 审计事件持久化表 audit_events（P2 §2.1）。

Revision ID: 0011
Revises: 0010
Create Date: 2026-06-09
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0011"
down_revision: str | Sequence[str] | None = "0010"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_id", sa.String(length=64), nullable=False, comment="事件UUID(幂等键)"),
        sa.Column(
            "schema_version", sa.String(length=32), nullable=False, comment="envelope schema版本"
        ),
        sa.Column("event_type", sa.String(length=32), nullable=False, comment="事件类型(枚举)"),
        sa.Column("action", sa.String(length=128), nullable=False, comment="权限点/操作标识"),
        sa.Column("title", sa.String(length=256), nullable=False, comment="人读操作标题"),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="事件发生时刻(UTC,来自envelope)",
        ),
        sa.Column(
            "actor_user_id", sa.BigInteger(), nullable=True, comment="操作者用户ID(快照,无FK)"
        ),
        sa.Column(
            "actor_username", sa.String(length=64), nullable=True, comment="操作者用户名(快照)"
        ),
        sa.Column("actor_is_super_admin", sa.Boolean(), nullable=False, comment="操作者是否超管"),
        sa.Column("target_type", sa.String(length=64), nullable=True, comment="作用对象类型"),
        sa.Column("target_id", sa.String(length=128), nullable=True, comment="作用对象ID"),
        sa.Column("target_display", sa.String(length=255), nullable=True, comment="作用对象显示名"),
        sa.Column("request_id", sa.String(length=64), nullable=True, comment="请求ID(关联键)"),
        sa.Column("trace_id", sa.String(length=64), nullable=True, comment="trace ID"),
        sa.Column("method", sa.String(length=16), nullable=True, comment="HTTP方法"),
        sa.Column("path", sa.String(length=512), nullable=True, comment="请求路径"),
        sa.Column("ip", sa.String(length=64), nullable=True, comment="客户端IP"),
        sa.Column("user_agent", sa.String(length=512), nullable=True, comment="User-Agent"),
        sa.Column(
            "result_status",
            sa.String(length=16),
            nullable=False,
            comment="结果(success/failure/denied)",
        ),
        sa.Column("result_http_status", sa.Integer(), nullable=True, comment="HTTP状态码"),
        sa.Column("result_error_code", sa.String(length=128), nullable=True, comment="错误码"),
        sa.Column("duration_ms", sa.Integer(), nullable=True, comment="耗时(毫秒)"),
        sa.Column(
            "risk_level", sa.String(length=16), nullable=False, comment="风险等级(low/medium/high)"
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="脱敏后业务负载(JSONB)",
        ),
        sa.Column("redaction_applied", sa.Boolean(), nullable=False, comment="是否发生过脱敏"),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="完整envelope(无损取证)",
        ),
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="创建时间(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="更新时间(UTC, ORM flush 触发)",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id"),
    )
    op.create_index(
        "ix_audit_events_actor_time", "audit_events", ["actor_user_id", "occurred_at"], unique=False
    )
    op.create_index("ix_audit_events_occurred_at", "audit_events", ["occurred_at"], unique=False)
    op.create_index("ix_audit_events_request_id", "audit_events", ["request_id"], unique=False)
    op.create_index(
        "ix_audit_events_result_status", "audit_events", ["result_status"], unique=False
    )
    op.create_index(
        "ix_audit_events_type_time", "audit_events", ["event_type", "occurred_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_type_time", table_name="audit_events")
    op.drop_index("ix_audit_events_result_status", table_name="audit_events")
    op.drop_index("ix_audit_events_request_id", table_name="audit_events")
    op.drop_index("ix_audit_events_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_time", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
