"""p2_login_logs —— 登录日志表 login_logs（P2 §2.2，RuoYi sys_logininfor 对标）。

Revision ID: 0012
Revises: 0011
Create Date: 2026-06-09
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: str | Sequence[str] | None = "0011"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_logs",
        sa.Column("username", sa.String(length=64), nullable=False, comment="尝试登录的用户名"),
        sa.Column(
            "user_id", sa.BigInteger(), nullable=True, comment="用户ID(失败/不存在时可空,无FK)"
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            comment="success/failure/locked/rate_limited/captcha_required",
        ),
        sa.Column(
            "reason_code", sa.String(length=64), nullable=True, comment="失败原因码(error_code)"
        ),
        sa.Column("ip", sa.String(length=64), nullable=True, comment="客户端IP"),
        sa.Column("user_agent", sa.String(length=512), nullable=True, comment="User-Agent"),
        sa.Column(
            "request_id", sa.String(length=64), nullable=True, comment="请求ID(关联audit_events)"
        ),
        sa.Column(
            "login_at_utc", sa.DateTime(timezone=True), nullable=False, comment="登录尝试时刻(UTC)"
        ),
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="创建时间(UTC)",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="更新时间(UTC, ORM flush 触发)",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_login_logs_login_at", "login_logs", ["login_at_utc"], unique=False)
    op.create_index("ix_login_logs_status", "login_logs", ["status"], unique=False)
    op.create_index(
        "ix_login_logs_user_time", "login_logs", ["user_id", "login_at_utc"], unique=False
    )
    op.create_index(
        "ix_login_logs_username_time", "login_logs", ["username", "login_at_utc"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_login_logs_username_time", table_name="login_logs")
    op.drop_index("ix_login_logs_user_time", table_name="login_logs")
    op.drop_index("ix_login_logs_status", table_name="login_logs")
    op.drop_index("ix_login_logs_login_at", table_name="login_logs")
    op.drop_table("login_logs")
    # ### end Alembic commands ###
