"""审计事件契约机检（spec §13.3 / §9 DoD 补，DB-free）。

冻结 ``audit_event.v1`` 字段 + 三类事件可表达 + 脱敏双层（敏感字段绝不出现在 dump）。
"""

from __future__ import annotations

import json

import pytest

from admin_platform.audit.emit import build_audit_event
from admin_platform.audit.events import (
    SCHEMA_VERSION,
    AuditActor,
    AuditEvent,
    AuditResult,
    AuditTarget,
    redact_metadata,
)

# v1 冻结字段（spec §13.3）—— 改动即破契约，机检守门。
_V1_FIELDS = {
    "schema_version",
    "event_id",
    "event_type",
    "action",
    "title",
    "occurred_at_utc",
    "actor",
    "target",
    "request",
    "result",
    "duration_ms",
    "risk_level",
    "metadata",
    "redaction_applied",
}


def test_v1_envelope_has_frozen_fields() -> None:
    ev = build_audit_event(
        event_type="permission_denied",
        action="system:user:list",
        title="权限拒绝",
        result=AuditResult(status="denied", http_status=403, error_code="auth.FORBIDDEN_BY_ROLE"),
    )
    dumped = ev.model_dump(mode="json")
    assert set(dumped.keys()) == _V1_FIELDS
    assert dumped["schema_version"] == SCHEMA_VERSION == "audit_event.v1"
    assert {"user_id", "username", "is_super_admin"} <= set(dumped["actor"].keys())
    assert {"request_id", "trace_id", "method", "path", "ip", "user_agent"} <= set(
        dumped["request"].keys()
    )


@pytest.mark.parametrize(
    "event_type",
    ["permission_denied", "login_failed", "rbac_write"],
)
def test_all_three_event_types_produce_v1(event_type: str) -> None:
    ev = build_audit_event(
        event_type=event_type,  # type: ignore[arg-type]
        action="x",
        title="t",
        result=AuditResult(status="failure"),
    )
    assert isinstance(ev, AuditEvent)
    assert ev.schema_version == "audit_event.v1"
    assert ev.event_type == event_type


def test_redact_metadata_drops_sensitive_keys() -> None:
    cleaned, redacted = redact_metadata(
        {
            "Authorization": "Bearer xxx",
            "password": "secret",
            "access_token": "tok",
            "Cookie": "sid=1",
            "api_key": "k",
            "username": "alice",  # 非敏感，保留
            "dept_id": 3,
        }
    )
    assert redacted is True
    assert cleaned == {"username": "alice", "dept_id": 3}


def test_no_sensitive_field_in_event_dump() -> None:
    # 即使把敏感数据塞进 metadata，构造后 dump 的 JSON 里也不能出现敏感值。
    ev = build_audit_event(
        event_type="login_failed",
        action="auth.login",
        title="登录失败",
        actor=AuditActor(),
        target=AuditTarget(type="user", display="alice"),
        result=AuditResult(status="failure", http_status=401, error_code="auth.LOGIN_FAILED"),
        metadata={"password": "super-secret-pw", "token": "leaked-token", "ok": "kept"},
    )
    blob = json.dumps(ev.model_dump(mode="json"), ensure_ascii=False)
    assert "super-secret-pw" not in blob
    assert "leaked-token" not in blob
    assert ev.redaction_applied is True
    assert ev.metadata == {"ok": "kept"}


def test_event_id_and_timestamp_autogenerated() -> None:
    ev = build_audit_event(
        event_type="rbac_write",
        action="system:role:add",
        title="角色新增",
        result=AuditResult(status="success", http_status=201),
    )
    assert ev.event_id  # uuid4 非空
    assert ev.occurred_at_utc.endswith(("Z", "+00:00"))  # ISO UTC
